doctrine:
    dbal:
        driver: 'pdo_postgresql'
        server_version: '10.9'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            user_id: 'App\Infrastructure\Doctrine\Type\UserIdType'
            company_id: 'App\Infrastructure\Doctrine\Type\CompanyIdType'
            officer_id: 'App\Infrastructure\Doctrine\Type\OfficerIdType'
            jurisdiction: 'App\Infrastructure\Doctrine\Type\JurisdictionType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Model'
                prefix: App\Domain\Model
                alias: App
